### ISSUE TITLE
Bots moving between the same points

### ISSUE THREAD

**Issue by DrakiaXYZ** [DrakiaXYZ/SPT-Waypoints#11]
Sometimes a bot will get stuck moving between the same few points, instead of patrolling further away. I don't change anything in regards to point selection, so this may be something broken in the base game logic. Or maybe just a really small patrol path with only a few points? Will need to look into it

**Comment by Solarint** [comment]
Any patrols done by me have a minimum of around 5 points in them iirc. None should have only 2.

**Comment by DrakiaXYZ** [comment]
Perfect, thanks! I've been distracted by other things so haven't had a chance to look into this yet

**Comment by DrakiaXYZ** [comment]
No longer an issue as Waypoints no longer overrides patrols
