### ISSUE TITLE
Rebuild Meshes without Gates

### ISSUE THREAD

**Issue by dwesterwick** [DrakiaXYZ/SPT-Waypoints#20]
Apparently BSG generates NavMeshes without gates, elevator doors, etc. in place. If they aren't removed before generating the mesh, those objects create breaks in it, and bots will be unable to travel behind them. However, if the NavMesh is generated without those objects, NavMeshObstacles need to be attached to them. Otherwise, bots will be dumb and run into them. 

I've confirmed this is happening in the following areas in SPT 3.7.6:
* All exfil gates in Labs (i.e. Parking Gate)
* All elevator doors in Labs (i.e. Cargo Elevator)
* D2 sliding door in Reserve

**Comment by DrakiaXYZ** [comment]
3.8.0 generation of Labs will have elevator and rolling shutter doors (Garage and hangar) removed

Will be looking at D2 when I get to Reserve.
Will be looking at dynamic blockers as well

**Comment by DrakiaXYZ** [comment]
Done
