### ISSUE TITLE
Eliminate Areas Requiring Crouching from NavMesh

### ISSUE THREAD

**Issue by dwesterwick** [DrakiaXYZ/SPT-Waypoints#21]
Some map prefabs like the children's play centers have features that are too low for bots to walk under, and they're too dumb to crouch. Instead, they think they can walk through the feature, but they actually just run up against it. BSG eliminates these areas from their meshes. 

For example, this is BSG's NavMesh:
![2024-02-11 00-09 _-99 5, 25 2, -113 3_0 1, 0 9, -0 3, 0 2_12 38 (0)](https://github.com/DrakiaXYZ/SPT-Waypoints/assets/94018859/cfc9e079-6ab9-4b40-89e5-5f251fd2cf6a)

In contrast, this is Waypoints' NavMesh:
![2024-02-11 00-11 _-99 3, 23 8, -113 1_0 0, 1 0, -0 2, 0 2_12 69 (0)](https://github.com/DrakiaXYZ/SPT-Waypoints/assets/94018859/ca92a79c-5742-4c0c-9f24-64039c66aba7)

This is the result:
![2024-02-10 22-43 _-100 1, 24 1, -114 0_0 1, 0 9, -0 3, 0 2_11 27 (0)](https://github.com/DrakiaXYZ/SPT-Waypoints/assets/94018859/44a0745d-27c4-4ef5-a159-e9d1ee7b327b)

**Comment by DrakiaXYZ** [comment]
Updated meshes will be generated with a player height more in-line with what BSG uses (1.7m), which should resolve this. However I'll keep an eye on Streets when I generate that mesh
